use super::language::EggSmt;
use egg::{rewrite, Analysis, Rewrite};

/// Rewrite rules which increase the size of the E-Graph exponentially.
pub fn expansion_rules<A: Analysis<EggSmt>>() -> Vec<Rewrite<EggSmt, A>> {
    vec![
        // Boolean Rules
        // From Theorem 2 page 35 of
        // "Discrete Mathematics: Mathematical Reasoning and Proof with Puzzles, Patterns, and Games"
        // by Douglas E. Ensley and J. Winston Crawley
        rewrite! {"commutative_and";     "(and ?p ?q)"          => "(and ?q ?p)"},
        rewrite! {"commutative_or";      "(or ?p ?q)"           => "(or ?q ?p)"},
        //
        rewrite! {"associative_and";     "(and (and ?p ?q) ?r)" => "(and ?p (and ?q ?r))"},
        rewrite! {"associative_or";      "(or (or ?p ?q) ?r)"   => "(or ?p (or ?q ?r))"},
        //
        rewrite! {"distributive_and_or"; "(and ?p (or ?q ?r))"  => "(or (and ?p ?q) (and ?p ?r))"},
        rewrite! {"distributive_or_and"; "(or ?p (and ?q ?r))"  => "(and (or ?p ?q) (or ?p ?r))"},
        //
        rewrite! {"demorgans_and";       "(not (and ?p ?q))"    => "(or (not ?p) (not ?q))"},
        rewrite! {"demorgans_or";        "(not (or ?p ?q))"     => "(and (not ?p) (not ?q))"},
        //
        // Added Rules
        rewrite! {"implicate";           "(or (not ?a) ?b)"     => "(=> ?a ?b)"},
        rewrite! {"deimplicate";         "(=> ?a ?b)"           => "(or (not ?a) ?b)"},
        rewrite! {"commutative_eq";      "(= ?a ?b)"            => "(= ?b ?a)"},
        rewrite! {"yash_pote";   "(or (and ?a ?b) (and ?a ?c))" => "(and ?a (or ?b ?c))"},
    ]
}

/// Rewrite rules which linearly increase the size of the E-GRaph, or may shrink it.
pub fn reduction_rules<A: Analysis<EggSmt>>() -> Vec<Rewrite<EggSmt, A>> {
    vec![
        // Boolean Rules
        // From Theorem 2 page 35 of
        // "Discrete Mathematics: Mathematical Reasoning and Proof with Puzzles, Patterns, and Games"
        // by Douglas E. Ensley and J. Winston Crawley
        rewrite! {"identity_and";        "(and ?p true)"       => "?p"},
        rewrite! {"identity_or";         "(or ?p false)"       => "?p"},
        //
        rewrite! {"negation_and";        "(and ?p (not ?p))"   => "false"},
        rewrite! {"negation_or";         "(or ?p (not ?p))"    => "true"},
        //
        rewrite! {"double_negative";     "(not (not ?p))"      => "?p"},
        //
        rewrite! {"idempotent_and";      "(and ?p ?p)"         => "?p"},
        rewrite! {"idempotent_or";       "(or ?p ?p)"          => "?p"},
        //
        rewrite! {"universal_bound_and";  "(and ?p false)"     => "false"},
        rewrite! {"universal_bound_or";   "(or ?p true)"       => "true"},
        //
        rewrite! {"absorption_and";      "(and ?p (or ?p ?q))" => "?p"},
        rewrite! {"absorption_or";       "(or ?p (and ?p ?q))" => "?p"},
        //
        rewrite! {"negation_true";       "(not true)"          => "false"},
        rewrite! {"negation_false";      "(not false)"         => "true"},
        //
        // Added rules
        rewrite! {"imply_same";          "(=> ?a (or ?a ?b))"  => "true"},
        rewrite! {"eq_refl";             "(= ?a ?a)"           => "true"},
        rewrite! {"eq_true";             "(= true ?a)"         => "?a"},
        rewrite! {"eq_false";            "(= false ?a)"        => "(not ?a)"},
        rewrite! {"ite_true";            "(ite true ?a ?b)"    => "?a"},
        rewrite! {"ite_false";           "(ite false ?a ?b)"   => "?b"},
        rewrite! {"illusion_of_choice";  "(ite ?a ?b ?b)"      => "?b"},
        // Regex Rewrites
        rewrite! {"re_combine"; "(re.++ (str.to_re ?l) (str.to_re ?r))" => "(str.to_re (str.++ ?l ?r))"},
        rewrite! {"kevin_lotz"; "(str.in_re ?s (re.++ (str.to_re ?p) (re.* re.allchar)))" => "(str.prefixof ?p ?s)"},
        rewrite! {"glob"; "(str.in_re ?s (re.* re.allchar))" => "true"},
        // BV rewrites
        rewrite! {""; "(bvsub (bvor ?a 1) ?a)" => "(bvlshr 1 (bvand ?a 1))"},
        rewrite! {""; "(bvadd (bvshl ?a ?a) 1)" => "(bvor (bvshl ?a ?a) 1)"},
        rewrite! {""; "(bvor (bvshl ?a ?a) 1)" => "(bvadd (bvshl ?a ?a) 1)"},
        rewrite! {""; "(bvadd 1 (bvand ?a 1))" => "(bvshl 1 (bvand ?a 1))"},
        rewrite! {""; "(bvshl 1 (bvand ?a 1))" => "(bvadd 1 (bvand ?a 1))"},
        rewrite! {""; "(bvlshr (bvadd ?a 1) ?a)" => "(bvlshr 1 (bvlshr ?a 1))"},
        rewrite! {""; "(bvlshr 1 (bvlshr ?a 1))" => "(bvlshr (bvadd ?a 1) ?a)"},
        rewrite! {""; "(bvlshr ?a (bvadd 1 1))" => "(bvlshr (bvlshr ?a 1) 1)"},
        rewrite! {""; "(bvlshr (bvlshr ?a 1) 1)" => "(bvlshr ?a (bvadd 1 1))"},
        rewrite! {""; "(bvshl ?a (bvadd 1 1))" => "(bvshl (bvadd ?a ?a) 1)"},
        rewrite! {""; "(bvshl (bvadd ?a ?a) 1)" => "(bvshl ?a (bvadd 1 1))"},
        rewrite! {""; "(bvlshr 1 (bvlshr 1 ?a))" => "(bvsub 1 (bvlshr 1 ?a))"},
        rewrite! {""; "(bvsub 1 (bvlshr 1 ?a))" => "(bvlshr 1 (bvlshr 1 ?a))"},
        rewrite! {""; "(bvand ?a (bvnot 1))" => "(bvshl (bvlshr ?a 1) 1)"},
        rewrite! {""; "(bvshl (bvlshr ?a 1) 1)" => "(bvand ?a (bvnot 1))"},
        rewrite! {""; "(bvlshr 1 (bvand ?a 1))" => "(bvand (bvnot ?a) 1)"},
        rewrite! {""; "(bvand (bvnot ?a) 1)" => "(bvlshr 1 (bvand ?a 1))"},
        rewrite! {""; "(bvlshr 1 ?a)" => "(bvshl (bvlshr 1 ?a) ?a)"},
        rewrite! {""; "(bvshl (bvlshr 1 ?a) ?a)" => "(bvlshr 1 ?a)"},
        rewrite! {""; "(bvlshr ?a (bvsub ?a 1))" => "(bvlshr (bvadd ?a ?a) ?a)"},
        rewrite! {""; "(bvlshr (bvadd ?a ?a) ?a)" => "(bvlshr ?a (bvsub ?a 1))"},
        rewrite! {""; "(bvshl (bvand ?a 1) ?a)" => "(bvshl (bvmul ?a ?a) ?a)"},
        rewrite! {""; "(bvshl (bvmul ?a ?a) ?a)" => "(bvshl (bvand ?a 1) ?a)"},
        rewrite! {""; "(bvshl ?a (bvor ?a 1))" => "(bvshl (bvmul ?a ?a) ?a)"},
        rewrite! {""; "(bvshl (bvmul ?a ?a) ?a)" => "(bvshl ?a (bvor ?a 1))"},
        rewrite! {""; "(bvlshr ?a (bvshl ?a ?a))" => "(bvlshr ?a (bvshl 1 ?a))"},
        rewrite! {""; "(bvlshr ?a (bvshl 1 ?a))" => "(bvlshr ?a (bvshl ?a ?a))"},
        rewrite! {""; "(bvshl ?a (bvshl ?a ?a))" => "(bvshl ?a (bvshl 1 ?a))"},
        rewrite! {""; "(bvshl ?a (bvshl 1 ?a))" => "(bvshl ?a (bvshl ?a ?a))"},
        rewrite! {""; "(bvor 1 (bvadd ?a ?a))" => "(bvsub ?a (bvnot ?a))"},
        rewrite! {""; "(bvsub ?a (bvnot ?a))" => "(bvor 1 (bvadd ?a ?a))"},
        rewrite! {""; "(bvlshr (bvnot ?a) (bvneg ?a))" => "(bvneg (bvlshr 1 ?a))"},
        rewrite! {""; "(bvneg (bvlshr 1 ?a))" => "(bvlshr (bvnot ?a) (bvneg ?a))"},
        rewrite! {""; "(bvshl (bvadd ?a ?a) ?a)" => "(bvshl (bvshl ?a ?a) ?a)"},
        rewrite! {""; "(bvshl (bvshl ?a ?a) ?a)" => "(bvshl (bvadd ?a ?a) ?a)"},
        rewrite! {""; "(bvneg (bvor ?a (bvneg ?a)))" => "(bvand ?a (bvneg ?a))"},
        rewrite! {""; "(bvand ?a (bvneg ?a))" => "(bvneg (bvor ?a (bvneg ?a)))"},
        rewrite! {""; "(bvand (bvshl ?b ?a) 1)" => "(bvlshr (bvand ?b 1) ?a)"},
        rewrite! {""; "(bvlshr (bvand ?b 1) ?a)" => "(bvand (bvshl ?b ?a) 1)"},
        rewrite! {""; "(bvand (bvsub ?b ?a) 1)" => "(bvand (bvadd ?b ?a) 1)"},
        rewrite! {""; "(bvand (bvadd ?b ?a) 1)" => "(bvand (bvsub ?b ?a) 1)"},
        rewrite! {""; "(bvand ?b (bvlshr 1 ?a))" => "(bvlshr (bvand ?b 1) ?a)"},
        rewrite! {""; "(bvlshr (bvand ?b 1) ?a)" => "(bvand ?b (bvlshr 1 ?a))"},
        rewrite! {""; "(bvand (bvmul ?b ?a) 1)" => "(bvand (bvand ?b ?a) 1)"},
        rewrite! {""; "(bvand (bvand ?b ?a) 1)" => "(bvand (bvmul ?b ?a) 1)"},
        rewrite! {""; "(bvlshr 1 (bvor ?b ?a))" => "(bvlshr (bvlshr 1 ?a) ?b)"},
        rewrite! {""; "(bvlshr (bvlshr 1 ?a) ?b)" => "(bvlshr 1 (bvor ?b ?a))"},
        rewrite! {""; "(bvsub ?a (bvmul ?b ?a))" => "(bvmul ?a (bvsub 1 ?b))"},
        rewrite! {""; "(bvmul ?a (bvsub 1 ?b))" => "(bvsub ?a (bvmul ?b ?a))"},
        rewrite! {""; "(bvmul (bvnot ?b) (bvneg ?a))" => "(bvadd ?a (bvmul ?b ?a))"},
        rewrite! {""; "(bvadd ?a (bvmul ?b ?a))" => "(bvmul (bvnot ?b) (bvneg ?a))"},
        rewrite! {""; "(bvand ?a (bvor ?b ?a))" => "(bvsub (bvadd ?b ?a) ?b)"},
        rewrite! {""; "(bvsub (bvadd ?b ?a) ?b)" => "(bvand ?a (bvor ?b ?a))"},
        rewrite! {""; "(bvadd ?a (bvshl ?b ?a))" => "(bvor ?a (bvshl ?b ?a))"},
        rewrite! {""; "(bvor ?a (bvshl ?b ?a))" => "(bvadd ?a (bvshl ?b ?a))"},
        rewrite! {""; "(bvand ?a (bvshl ?b ?a))" => "(bvand ?b (bvshl ?a ?b))"},
        rewrite! {""; "(bvand ?b (bvshl ?a ?b))" => "(bvand ?a (bvshl ?b ?a))"},
        rewrite! {""; "(bvlshr (bvlshr ?a ?b) ?a)" => "(bvlshr (bvand ?b ?a) ?b)"},
        rewrite! {""; "(bvlshr (bvand ?b ?a) ?b)" => "(bvlshr (bvlshr ?a ?b) ?a)"},
        rewrite! {""; "(bvlshr (bvlshr ?a ?b) ?a)" => "(bvlshr ?a (bvor ?a ?b))"},
        rewrite! {""; "(bvlshr ?a (bvor ?a ?b))" => "(bvlshr (bvlshr ?a ?b) ?a)"},
        rewrite! {""; "(bvnot (bvand ?b (bvnot ?a)))" => "(bvor ?a (bvnot ?b))"},
        rewrite! {""; "(bvor ?a (bvnot ?b))" => "(bvnot (bvand ?b (bvnot ?a)))"},
        rewrite! {""; "(bvand ?b (bvnot ?a))" => "(bvsub ?b (bvand ?a ?b))"},
        rewrite! {""; "(bvsub ?b (bvand ?a ?b))" => "(bvand ?b (bvnot ?a))"},
        rewrite! {""; "(bvlshr ?b ?a)" => "(bvlshr (bvor ?b ?a) ?a)"},
        rewrite! {""; "(bvlshr (bvor ?b ?a) ?a)" => "(bvlshr ?b ?a)"},
        rewrite! {""; "(bvsub ?c (bvadd ?b ?a))" => "(bvsub (bvsub ?c ?a) ?b)"},
        rewrite! {""; "(bvsub (bvsub ?c ?a) ?b)" => "(bvsub ?c (bvadd ?b ?a))"},
        rewrite! {""; "(bvshl (bvmul ?c ?b) ?a)" => "(bvmul ?b (bvshl ?c ?a))"},
        rewrite! {""; "(bvmul ?b (bvshl ?c ?a))" => "(bvshl (bvmul ?c ?b) ?a)"},
        rewrite! {""; "(bvand ?c (bvand ?b ?a))" => "(bvand ?b (bvand ?a ?c))"},
        rewrite! {""; "(bvand ?b (bvand ?a ?c))" => "(bvand ?c (bvand ?b ?a))"},
        rewrite! {""; "(bvmul ?c (bvmul ?b ?a))" => "(bvmul ?a (bvmul ?b ?c))"},
        rewrite! {""; "(bvmul ?a (bvmul ?b ?c))" => "(bvmul ?c (bvmul ?b ?a))"},
        rewrite! {""; "(bvshl (bvshl ?c ?a) ?b)" => "(bvshl (bvshl ?c ?b) ?a)"},
        rewrite! {""; "(bvshl (bvshl ?c ?b) ?a)" => "(bvshl (bvshl ?c ?a) ?b)"},
        rewrite! {""; "(bvsub (bvsub ?c ?a) ?b)" => "(bvsub (bvsub ?c ?b) ?a)"},
        rewrite! {""; "(bvsub (bvsub ?c ?b) ?a)" => "(bvsub (bvsub ?c ?a) ?b)"},
        rewrite! {""; "(bvlshr (bvlshr ?c ?a) ?b)" => "(bvlshr (bvlshr ?c ?b) ?a)"},
        rewrite! {""; "(bvlshr (bvlshr ?c ?b) ?a)" => "(bvlshr (bvlshr ?c ?a) ?b)"},
        rewrite! {""; "(bvor ?b (bvor ?c ?a))" => "(bvor ?c (bvor ?b ?a))"},
        rewrite! {""; "(bvor ?c (bvor ?b ?a))" => "(bvor ?b (bvor ?c ?a))"},
        rewrite! {""; "(bvneg (bvor ?a 1))" => "(bvor (bvnot ?a) 1)"},
        rewrite! {""; "(bvor (bvnot ?a) 1)" => "(bvneg (bvor ?a 1))"},
        rewrite! {""; "(bvlshr 1 ?a)" => "(bvlshr 1 (bvneg ?a))"},
        rewrite! {""; "(bvlshr 1 (bvneg ?a))" => "(bvlshr 1 ?a)"},
        rewrite! {""; "(bvand ?a 1)" => "(bvand (bvneg ?a) 1)"},
        rewrite! {""; "(bvand (bvneg ?a) 1)" => "(bvand ?a 1)"},
        rewrite! {""; "(bvneg (bvadd ?a ?a))" => "(bvmul ?a (bvnot 1))"},
        rewrite! {""; "(bvmul ?a (bvnot 1))" => "(bvneg (bvadd ?a ?a))"},
        rewrite! {""; "(bvor ?a (bvnot ?a))" => "(bvor ?a (bvneg 1))"},
        rewrite! {""; "(bvor ?a (bvneg 1))" => "(bvor ?a (bvnot ?a))"},
        rewrite! {""; "(bvadd ?a (bvneg ?a))" => "(bvshl ?a (bvneg 1))"},
        rewrite! {""; "(bvshl ?a (bvneg 1))" => "(bvadd ?a (bvneg ?a))"},
        rewrite! {""; "(bvadd ?a (bvneg ?a))" => "(bvlshr ?a (bvneg 1))"},
        rewrite! {""; "(bvlshr ?a (bvneg 1))" => "(bvadd ?a (bvneg ?a))"},
        rewrite! {""; "(bvshl ?a (bvnot 1))" => "(bvand ?a (bvnot ?a))"},
        rewrite! {""; "(bvand ?a (bvnot ?a))" => "(bvshl ?a (bvnot 1))"},
        rewrite! {""; "(bvand ?a (bvnot ?a))" => "(bvlshr ?a (bvnot 1))"},
        rewrite! {""; "(bvlshr ?a (bvnot 1))" => "(bvand ?a (bvnot ?a))"},
        rewrite! {""; "(bvlshr (bvneg 1) ?a)" => "(bvlshr (bvnot ?a) ?a)"},
        rewrite! {""; "(bvlshr (bvnot ?a) ?a)" => "(bvlshr (bvneg 1) ?a)"},
        rewrite! {""; "?a" => "(bvand ?a (bvneg 1))"},
        rewrite! {""; "(bvand ?a (bvneg 1))" => "?a"},
        rewrite! {""; "(bvadd ?a (bvneg ?a))" => "(bvand ?a (bvnot ?a))"},
        rewrite! {""; "(bvand ?a (bvnot ?a))" => "(bvadd ?a (bvneg ?a))"},
        rewrite! {""; "(bvor ?a (bvnot ?a))" => "(bvadd ?a (bvnot ?a))"},
        rewrite! {""; "(bvadd ?a (bvnot ?a))" => "(bvor ?a (bvnot ?a))"},
        rewrite! {""; "(bvsub (bvnot ?b) ?a)" => "(bvnot (bvadd ?a ?b))"},
        rewrite! {""; "(bvnot (bvadd ?a ?b))" => "(bvsub (bvnot ?b) ?a)"},
        rewrite! {""; "(bvneg (bvmul ?b ?a))" => "(bvmul ?a (bvneg ?b))"},
        rewrite! {""; "(bvmul ?a (bvneg ?b))" => "(bvneg (bvmul ?b ?a))"},
        rewrite! {""; "(bvshl (bvneg ?b) ?a)" => "(bvneg (bvshl ?b ?a))"},
        rewrite! {""; "(bvneg (bvshl ?b ?a))" => "(bvshl (bvneg ?b) ?a)"},
        rewrite! {""; "(bvsub (bvnot ?b) ?a)" => "(bvsub (bvnot ?a) ?b)"},
        rewrite! {""; "(bvsub (bvnot ?a) ?b)" => "(bvsub (bvnot ?b) ?a)"},
        rewrite! {""; "(bvadd ?b ?a)" => "(bvsub ?a (bvneg ?b))"},
        rewrite! {""; "(bvsub ?a (bvneg ?b))" => "(bvadd ?b ?a)"},
        rewrite! {""; "(bvneg (bvsub ?b ?a))" => "(bvsub ?a ?b)"},
        rewrite! {""; "(bvsub ?a ?b)" => "(bvneg (bvsub ?b ?a))"},
        rewrite! {""; "(bvmul ?a ?b)" => "(bvmul ?b ?a)"},
        rewrite! {""; "(bvmul ?b ?a)" => "(bvmul ?a ?b)"},
        rewrite! {""; "(bvand ?a ?b)" => "(bvand ?b ?a)"},
        rewrite! {""; "(bvand ?b ?a)" => "(bvand ?a ?b)"},
        rewrite! {""; "(bvadd ?a ?b)" => "(bvadd ?b ?a)"},
        rewrite! {""; "(bvadd ?b ?a)" => "(bvadd ?a ?b)"},
        rewrite! {""; "(bvor ?a ?b)" => "(bvor ?b ?a)"},
        rewrite! {""; "(bvor ?b ?a)" => "(bvor ?a ?b)"},
        rewrite! {""; "(bvneg (bvneg ?a))" => "?a"},
        rewrite! {""; "?a" => "(bvneg (bvneg ?a))"},
        rewrite! {""; "(bvor ?a ?a)" => "?a"},
        rewrite! {""; "?a" => "(bvor ?a ?a)"},
        rewrite! {""; "(bvnot (bvnot ?a))" => "?a"},
        rewrite! {""; "?a" => "(bvnot (bvnot ?a))"},
        rewrite! {""; "(bvand ?a ?a)" => "?a"},
        rewrite! {""; "?a" => "(bvand ?a ?a)"},
        rewrite! {""; "(bvsub ?a ?a)" => "(bvlshr ?a ?a)"},
        rewrite! {""; "(bvlshr ?a ?a)" => "(bvsub ?a ?a)"},
        rewrite! {""; "(bvlshr ?a 0)" => "?a"},
        rewrite! {""; "?a" => "(bvlshr ?a 0)"},
        rewrite! {""; "(bvadd 0 ?a)" => "?a"},
        rewrite! {""; "?a" => "(bvadd 0 ?a)"},
        rewrite! {""; "(bvmul 1 ?a)" => "?a"},
        rewrite! {""; "?a" => "(bvmul 1 ?a)"},
        rewrite! {""; "(bvshl ?a 0)" => "?a"},
        rewrite! {""; "?a" => "(bvshl ?a 0)"},
        rewrite! {""; "(bvsub ?a 0)" => "?a"},
        rewrite! {""; "?a" => "(bvsub ?a 0)"},
        rewrite! {""; "(bvor 0 ?a)" => "?a"},
        rewrite! {""; "?a" => "(bvor 0 ?a)"},
        rewrite! {""; "(bvneg ?a)" => "(bvsub 0 ?a)"},
        rewrite! {""; "(bvsub 0 ?a)" => "(bvneg ?a)"},
        rewrite! {""; "(bvlshr 0 ?a)" => "(bvlshr ?a ?a)"},
        rewrite! {""; "(bvlshr ?a ?a)" => "(bvlshr 0 ?a)"},
        rewrite! {""; "(bvadd ?a ?a)" => "(bvshl ?a 1)"},
        rewrite! {""; "(bvshl ?a 1)" => "(bvadd ?a ?a)"},
        rewrite! {""; "(bvmul 0 ?a)" => "(bvsub ?a ?a)"},
        rewrite! {""; "(bvsub ?a ?a)" => "(bvmul 0 ?a)"},
        rewrite! {""; "(bvand 0 ?a)" => "(bvsub ?a ?a)"},
        rewrite! {""; "(bvsub ?a ?a)" => "(bvand 0 ?a)"},
        rewrite! {""; "(bvshl 0 ?a)" => "(bvsub ?a ?a)"},
        rewrite! {""; "(bvsub ?a ?a)" => "(bvshl 0 ?a)"},
        rewrite! {""; "(bvneg (bvnot ?a))" => "(bvadd ?a 1)"},
        rewrite! {""; "(bvadd ?a 1)" => "(bvneg (bvnot ?a))"},
        rewrite! {""; "(bvnot (bvneg ?a))" => "(bvsub ?a 1)"},
        rewrite! {""; "(bvsub ?a 1)" => "(bvnot (bvneg ?a))"},
        rewrite! {""; "(bvshl ?a (bvlshr (bvnot ?a) ?a))" => "(bvshl ?a (bvlshr (bvneg ?a) ?a))"},
        rewrite! {""; "(bvshl ?a (bvlshr (bvneg ?a) ?a))" => "(bvshl ?a (bvlshr (bvnot ?a) ?a))"},
        rewrite! {""; "(bvmul ?a (bvlshr (bvnot ?a) ?a))" => "(bvmul ?a (bvlshr (bvneg ?a) ?a))"},
        rewrite! {""; "(bvmul ?a (bvlshr (bvneg ?a) ?a))" => "(bvmul ?a (bvlshr (bvnot ?a) ?a))"},
        rewrite! {""; "(bvand (bvnot ?a) (bvadd ?a ?a))" => "(bvand (bvneg ?a) (bvadd ?a ?a))"},
        rewrite! {""; "(bvand (bvneg ?a) (bvadd ?a ?a))" => "(bvand (bvnot ?a) (bvadd ?a ?a))"},
        rewrite! {""; "(bvlshr ?a (bvlshr (bvnot ?a) ?a))" => "(bvlshr ?a (bvlshr (bvneg ?a) ?a))"},
        rewrite! {""; "(bvlshr ?a (bvlshr (bvneg ?a) ?a))" => "(bvlshr ?a (bvlshr (bvnot ?a) ?a))"},
        rewrite! {""; "(bvshl (bvsub (bvnot ?a) ?a) ?a)" => "(bvshl (bvnot (bvshl ?a ?a)) ?a)"},
        rewrite! {""; "(bvshl (bvnot (bvshl ?a ?a)) ?a)" => "(bvshl (bvsub (bvnot ?a) ?a) ?a)"},
        rewrite! {""; "(bvneg (bvnot (bvneg (bvmul ?a ?a))))" => "(bvmul (bvnot ?a) (bvnot (bvneg ?a)))"},
        rewrite! {""; "(bvmul (bvnot ?a) (bvnot (bvneg ?a)))" => "(bvneg (bvnot (bvneg (bvmul ?a ?a))))"},
        rewrite! {""; "(bvlshr (bvshl ?a ?a) ?a)" => "(bvand ?a (bvlshr (bvneg ?a) ?a))"},
        rewrite! {""; "(bvand ?a (bvlshr (bvneg ?a) ?a))" => "(bvlshr (bvshl ?a ?a) ?a)"},
        rewrite! {""; "(bvshl ?a (bvneg ?a))" => "(bvand ?a (bvshl ?a (bvneg ?a)))"},
        rewrite! {""; "(bvand ?a (bvshl ?a (bvneg ?a)))" => "(bvshl ?a (bvneg ?a))"},
        rewrite! {""; "(bvlshr (bvsub (bvneg ?a) ?a) ?a)" => "(bvlshr (bvneg ?a) ?a)"},
        rewrite! {""; "(bvlshr (bvneg ?a) ?a)" => "(bvlshr (bvsub (bvneg ?a) ?a) ?a)"},
        rewrite! {""; "(bvshl ?a ?a)" => "(bvshl (bvand ?a (bvneg ?a)) ?a)"},
        rewrite! {""; "(bvshl (bvand ?a (bvneg ?a)) ?a)" => "(bvshl ?a ?a)"},
        rewrite! {""; "(bvneg ?a)" => "(bvor (bvneg ?a) (bvshl ?a ?a))"},
        rewrite! {""; "(bvor (bvneg ?a) (bvshl ?a ?a))" => "(bvneg ?a)"},
        rewrite! {""; "(bvand (bvshl ?b (bvneg ?a)) ?a)" => "(bvshl (bvadd ?b ?b) (bvnot ?a))"},
        rewrite! {""; "(bvshl (bvadd ?b ?b) (bvnot ?a))" => "(bvand (bvshl ?b (bvneg ?a)) ?a)"},
        rewrite! {""; "(bvshl ?b (bvmul ?a (bvneg ?a)))" => "(bvlshr ?b (bvmul ?a (bvneg ?a)))"},
        rewrite! {""; "(bvlshr ?b (bvmul ?a (bvneg ?a)))" => "(bvshl ?b (bvmul ?a (bvneg ?a)))"},
        rewrite! {""; "(bvshl ?b (bvnot (bvmul ?a ?a)))" => "(bvshl ?b (bvnot (bvshl ?a ?a)))"},
        rewrite! {""; "(bvshl ?b (bvnot (bvshl ?a ?a)))" => "(bvshl ?b (bvnot (bvmul ?a ?a)))"},
        rewrite! {""; "(bvshl (bvlshr ?b ?a) (bvnot ?a))" => "(bvlshr ?b (bvnot (bvshl ?a ?a)))"},
        rewrite! {""; "(bvlshr ?b (bvnot (bvshl ?a ?a)))" => "(bvshl (bvlshr ?b ?a) (bvnot ?a))"},
        rewrite! {""; "(bvshl (bvlshr ?b (bvnot ?a)) ?a)" => "(bvlshr ?b (bvnot (bvshl ?a ?a)))"},
        rewrite! {""; "(bvlshr ?b (bvnot (bvshl ?a ?a)))" => "(bvshl (bvlshr ?b (bvnot ?a)) ?a)"},
        rewrite! {""; "(bvshl ?a (bvnot (bvlshr ?b ?a)))" => "(bvlshr ?a (bvnot (bvshl ?b ?b)))"},
        rewrite! {""; "(bvlshr ?a (bvnot (bvshl ?b ?b)))" => "(bvshl ?a (bvnot (bvlshr ?b ?a)))"},
        rewrite! {""; "(bvlshr ?b (bvnot (bvmul ?a ?a)))" => "(bvlshr ?b (bvnot (bvlshr ?a ?b)))"},
        rewrite! {""; "(bvlshr ?b (bvnot (bvlshr ?a ?b)))" => "(bvlshr ?b (bvnot (bvmul ?a ?a)))"},
        rewrite! {""; "(bvlshr ?a (bvnot (bvlshr ?b ?a)))" => "(bvlshr ?a (bvnot (bvshl ?b ?b)))"},
        rewrite! {""; "(bvlshr ?a (bvnot (bvshl ?b ?b)))" => "(bvlshr ?a (bvnot (bvlshr ?b ?a)))"},
        rewrite! {""; "(bvshl ?b (bvnot (bvshl ?a ?a)))" => "(bvlshr ?b (bvnot (bvshl ?a ?a)))"},
        rewrite! {""; "(bvlshr ?b (bvnot (bvshl ?a ?a)))" => "(bvshl ?b (bvnot (bvshl ?a ?a)))"},
        rewrite! {""; "(bvshl ?b (bvshl ?a (bvnot ?a)))" => "(bvshl ?b (bvshl ?a (bvneg ?a)))"},
        rewrite! {""; "(bvshl ?b (bvshl ?a (bvneg ?a)))" => "(bvshl ?b (bvshl ?a (bvnot ?a)))"},
        rewrite! {""; "(bvlshr ?b (bvshl (bvnot ?a) ?a))" => "(bvshl ?b (bvshl (bvnot ?a) ?a))"},
        rewrite! {""; "(bvshl ?b (bvshl (bvnot ?a) ?a))" => "(bvlshr ?b (bvshl (bvnot ?a) ?a))"},
        rewrite! {""; "(bvlshr ?b (bvneg (bvshl ?a ?a)))" => "(bvshl ?b (bvneg (bvshl ?a ?a)))"},
        rewrite! {""; "(bvshl ?b (bvneg (bvshl ?a ?a)))" => "(bvlshr ?b (bvneg (bvshl ?a ?a)))"},
        rewrite! {""; "(bvshl (bvshl ?b ?a) (bvneg ?a))" => "(bvshl ?b (bvor ?a (bvneg ?a)))"},
        rewrite! {""; "(bvshl ?b (bvor ?a (bvneg ?a)))" => "(bvshl (bvshl ?b ?a) (bvneg ?a))"},
        rewrite! {""; "(bvshl (bvshl ?b ?a) (bvneg ?a))" => "(bvlshr (bvlshr ?b ?a) (bvneg ?a))"},
        rewrite! {""; "(bvlshr (bvlshr ?b ?a) (bvneg ?a))" => "(bvshl (bvshl ?b ?a) (bvneg ?a))"},
        rewrite! {""; "(bvlshr (bvshl ?b (bvneg ?a)) ?a)" => "(bvlshr (bvlshr ?b ?a) (bvneg ?a))"},
        rewrite! {""; "(bvlshr (bvlshr ?b ?a) (bvneg ?a))" => "(bvlshr (bvshl ?b (bvneg ?a)) ?a)"},
        rewrite! {""; "(bvshl (bvlshr ?b (bvneg ?a)) ?a)" => "(bvlshr (bvlshr ?b ?a) (bvneg ?a))"},
        rewrite! {""; "(bvlshr (bvlshr ?b ?a) (bvneg ?a))" => "(bvshl (bvlshr ?b (bvneg ?a)) ?a)"},
        rewrite! {""; "(bvlshr ?b (bvor ?a (bvneg ?a)))" => "(bvlshr (bvlshr ?b ?a) (bvneg ?a))"},
        rewrite! {""; "(bvlshr (bvlshr ?b ?a) (bvneg ?a))" => "(bvlshr ?b (bvor ?a (bvneg ?a)))"},
        rewrite! {""; "(bvlshr (bvnot (bvshl ?b ?a)) ?a)" => "(bvlshr (bvshl (bvnot ?b) ?a) ?a)"},
        rewrite! {""; "(bvlshr (bvshl (bvnot ?b) ?a) ?a)" => "(bvlshr (bvnot (bvshl ?b ?a)) ?a)"},
        rewrite! {""; "(bvshl (bvnot (bvlshr ?b ?a)) ?a)" => "(bvshl (bvlshr (bvnot ?b) ?a) ?a)"},
        rewrite! {""; "(bvshl (bvlshr (bvnot ?b) ?a) ?a)" => "(bvshl (bvnot (bvlshr ?b ?a)) ?a)"},
        rewrite! {""; "(bvshl ?a (bvneg (bvlshr ?b ?a)))" => "(bvlshr ?a (bvneg (bvlshr ?b ?a)))"},
        rewrite! {""; "(bvlshr ?a (bvneg (bvlshr ?b ?a)))" => "(bvshl ?a (bvneg (bvlshr ?b ?a)))"},
        rewrite! {""; "(bvshl (bvshl ?b ?a) (bvnot ?a))" => "(bvshl ?b (bvnot (bvshl ?a ?a)))"},
        rewrite! {""; "(bvshl ?b (bvnot (bvshl ?a ?a)))" => "(bvshl (bvshl ?b ?a) (bvnot ?a))"},
        rewrite! {""; "(bvlshr (bvshl ?b ?a) ?a)" => "(bvand ?b (bvlshr (bvnot ?a) ?a))"},
        rewrite! {""; "(bvand ?b (bvlshr (bvnot ?a) ?a))" => "(bvlshr (bvshl ?b ?a) ?a)"},
        rewrite! {""; "(bvlshr ?a (bvshl ?b ?a))" => "(bvlshr ?a (bvneg (bvshl ?b ?a)))"},
        rewrite! {""; "(bvlshr ?a (bvneg (bvshl ?b ?a)))" => "(bvlshr ?a (bvshl ?b ?a))"},
        rewrite! {""; "(bvor (bvand ?b (bvnot ?a)) ?a)" => "(bvor ?b ?a)"},
        rewrite! {""; "(bvor ?b ?a)" => "(bvor (bvand ?b (bvnot ?a)) ?a)"},
        rewrite! {""; "(bvsub (bvadd ?a ?b) ?a)" => "(bvshl ?b (bvlshr 1 ?b))"},
        rewrite! {""; "(bvor ?a (bvand ?a ?b))" => "(bvlshr ?a (bvlshr 1 ?a))"},
        rewrite! {""; "(bvand ?a (bvshl ?b ?a))" => "(bvand (bvshl ?a ?a) 1)"},
        rewrite! {""; "(bvlshr (bvlshr ?b ?a) ?b)" => "(bvmul ?a (bvlshr 1 ?a))"},
        rewrite! {""; "(bvlshr (bvand ?a ?b) ?a)" => "(bvand ?b (bvlshr 1 ?b))"},
        rewrite! {""; "(bvlshr (bvlshr ?a ?b) ?a)" => "0"},
        rewrite! {""; "(bvlshr (bvand ?a ?b) ?b)" => "(bvand ?a (bvshl ?a ?a))"},
        rewrite! {""; "(bvand ?b (bvshl ?a ?b))" => "(bvand ?a (bvshl ?a ?a))"},
        rewrite! {""; "(bvor ?a (bvand ?b ?a))" => "?a"},
        rewrite! {""; "(bvand ?b (bvor ?b ?a))" => "?b"},
        rewrite! {""; "(bvor ?a (bvneg 1))" => "(bvneg 1)"},
        rewrite! {""; "(bvsub ?a ?a)" => "0"},
        rewrite! {""; "(bvor ?a (bvshl ?b (bvnot ?a)))" => "(bvor ?a (bvshl ?a (bvneg ?a)))"},
        rewrite! {""; "(bvshl ?a (bvnot (bvshl ?b ?b)))" => "(bvshl (bvshl ?a ?a) (bvneg ?a))"},
        rewrite! {""; "(bvlshr ?a (bvnot (bvshl ?b ?b)))" => "(bvlshr (bvshl ?a (bvnot ?a)) ?a)"},
        rewrite! {""; "(bvlshr ?a (bvnot (bvshl ?b ?b)))" => "(bvshl (bvlshr ?a (bvnot ?a)) ?a)"},
        rewrite! {""; "(bvshl ?a (bvnot (bvshl ?b ?b)))" => "(bvshl (bvshl ?a ?a) (bvnot ?a))"},
        rewrite! {""; "(bvshl ?a (bvnot (bvshl ?b ?b)))" => "(bvshl ?a (bvnot (bvshl ?a ?a)))"},
        rewrite! {""; "(bvlshr (bvnot (bvlshr ?a ?b)) ?a)" => "(bvlshr (bvnot ?a) ?a)"},
        rewrite! {""; "(bvor (bvshl ?b (bvnot ?a)) ?a)" => "?a"}
    ]
}
